Added CLI argument for `user-path`
BeamMP/BeamMP-Launcher pull request #148
Opened 2024-11-12 00:17 UTC by CodeCorrupt

Simple addition to the CLI args. It could probably do with some validation, ie; making sure it ends in a slash.

cc: @WiserTixx

2025-05-04 19:10 UTC, SaltySnail requested changes

2025-05-04 19:10 UTC, SaltySnail commented on src/GameStart.cpp
> +    Path = Path / (Ver + "\\");
Would this not break for linux users? It seems like you are appending a backslash

2025-05-04 19:24 UTC, WiserTixx commented on src/GameStart.cpp
> +    Path = Path / (Ver + "\\");
This function is for windows only, see line 31

2025-05-05 21:30 UTC, SaltySnail approved these changes
lgtm

2025-05-05 21:47 UTC, merged